dataInfo:

  camera:
    color:
      names: ['pikaGripperDepthCamera', 'pikaGripperFisheyeCamera']
      parentFrames: ['gripper/camera_link', 'gripper/camera_fisheye_link']
      topics: ['/gripper/camera/color/image_raw', '/gripper/camera_fisheye/color/image_raw']
      configTopics: ['/gripper/camera/color/camera_info', '/gripper/camera_fisheye/color/camera_info']
    depth:
      names: ['pikaGripperDepthCamera']
      parentFrames: ['gripper/camera_link']
      topics: ['/gripper/camera/aligned_depth_to_color/image_raw']
      configTopics: ['/gripper/camera/aligned_depth_to_color/camera_info']
    pointCloud:
      names: []
      parentFrames: []
      topics: []
      configTopics: []
      maxDistances: []
      downSizes: []

  arm:
    jointState:
      names: ['master', 'puppet']
      topics: ['/joint_states_gripper', '/joint_states_single_gripper']
    endPose:
      names: ['master', 'puppet']
      topics: ['/piper_IK/receive_end_pose_orient', '/piper_FK/urdf_end_pose_orient']
      orients: [true, true]

  localization:
    pose:
      names: ['pika']
      topics: ['/pika_pose']

  gripper:
    encoder:
      names: ['pikaSensor', 'pikaGripper']
      topics: ['/sensor/gripper/data', '/gripper/gripper/data']

  imu:
    9axis:
      names: []
      topics: []

  lidar:
    pointCloud:
      names: []
      topics: []
      xDistanceUppers: []
      xDistanceLowers: []
      yDistanceUppers: []
      yDistanceLowers: []
      zDistanceUppers: []
      zDistanceLowers: []
      downSizes: []

  robotBase:
    vel:
      names: []
      topics: []

  lift:
    motor:
      names: []
      topics: []
      pubTopics: []

  tf:
    transform:
      parentFrames: []
      childFrames: []
